import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./app/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
    "./lib/**/*.{ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        pitch: {
          50: "#f0fdf4",
          500: "#22c55e",
          700: "#15803d",
          900: "#14532d",
        },
        "on-error-container": "#93000a",
        "tertiary-fixed-dim": "#68d3fc",
        "secondary-fixed-dim": "#53e16f",
        "on-secondary-fixed-variant": "#00531c",
        "surface-container-lowest": "#ffffff",
        "background": "#fcf9f8",
        "surface-container-high": "#eae7e7",
        "primary-fixed": "#ffdad5",
        "on-tertiary": "#ffffff",
        "surface-tint": "#c0000a",
        "on-primary-fixed-variant": "#930005",
        "on-primary-fixed": "#410001",
        "surface-bright": "#fcf9f8",
        "secondary-container": "#6ffb85",
        "on-secondary-fixed": "#002107",
        "surface": "#fcf9f8",
        "tertiary": "#00647f",
        "on-error": "#ffffff",
        "surface-container-highest": "#e5e2e1",
        "on-tertiary-fixed": "#001f29",
        "surface-dim": "#dcd9d9",
        "on-tertiary-container": "#fafdff",
        "error": "#ba1a1a",
        "on-secondary": "#ffffff",
        "on-primary-container": "#fffbff",
        "secondary-fixed": "#72fe88",
        "outline-variant": "#e7bdb7",
        "secondary": "#006e28",
        "on-secondary-container": "#00732a",
        "surface-container": "#f0eded",
        "on-background": "#1c1b1b",
        "on-primary": "#ffffff",
        "surface-container-low": "#f6f3f2",
        "on-tertiary-fixed-variant": "#004d63",
        "primary-container": "#e2241f",
        "tertiary-fixed": "#bbe9ff",
        "error-container": "#ffdad6",
        "on-surface": "#1c1b1b",
        "on-surface-variant": "#5d3f3b",
        "tertiary-container": "#007fa0",
        "primary-fixed-dim": "#ffb4aa",
        "primary": "#bc000a",
        "outline": "#926f6a",
        "inverse-surface": "#313030",
        "inverse-on-surface": "#f3f0ef",
        "inverse-primary": "#ffb4aa",
        "surface-variant": "#e5e2e1"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "gutter": "24px",
        "lg": "48px",
        "base": "4px",
        "xs": "8px",
        "container-max": "1280px",
        "margin-mobile": "16px",
        "margin-desktop": "32px",
        "sm": "16px",
        "md": "24px",
        "xl": "80px"
      },
      fontFamily: {
        "body-md": ["Inter"],
        "body-sm": ["Inter"],
        "headline-md": ["Anybody"],
        "button": ["Anybody"],
        "display-lg": ["Anybody"],
        "headline-lg": ["Anybody"],
        "label-md": ["Inter"],
        "display-lg-mobile": ["Anybody"],
        "body-lg": ["Inter"]
      },
      fontSize: {
        "body-md": ["16px", { "lineHeight": "1.5", "fontWeight": "400" }],
        "body-sm": ["14px", { "lineHeight": "1.5", "fontWeight": "400" }],
        "headline-md": ["24px", { "lineHeight": "1.2", "fontWeight": "700" }],
        "button": ["14px", { "lineHeight": "1", "letterSpacing": "0.02em", "fontWeight": "700" }],
        "display-lg": ["48px", { "lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "800" }],
        "headline-lg": ["32px", { "lineHeight": "1.2", "fontWeight": "700" }],
        "label-md": ["12px", { "lineHeight": "1", "letterSpacing": "0.05em", "fontWeight": "600" }],
        "display-lg-mobile": ["36px", { "lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "800" }],
        "body-lg": ["18px", { "lineHeight": "1.6", "fontWeight": "400" }]
      }
    },
  },
  plugins: [],
};
export default config;
